#!/bin/bash
#basic navigation
alias home='cd ~'
alias homebin="cd ~/bin"
alias desk='cd ~/Desktop'
alias downloads='cd ~/Downloads'
alias library='cd ~/Library'
alias re='exec "$SHELL"'
# below is for development of this project
alias init="source /Users/sblanch/mybashscripts/osx/initGlobalSetup"
alias mybashscripts="cd ~/mybashscripts"
alias osx="mybashscripts; osx"
alias osxbin="osx; cd bin"
