#!/bin/bash

#basic navigation
alias desk="cd ~/Desktop"
alias downloads="cd ~/Downloads"
alias home="cd ~"

alias homescripts_cd_scripts="cd ~/homescripts"
alias homescripts_cd_aliases="cd ~/homescripts/aliases"
alias homescripts_cd_commands="cd ~/homescripts/commands"

alias homescripts_vim_aliases="vim ~/homescripts/aliases/homealiases"

