#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

source $SCRIPTPATH/initHomeEnvironmentVariables
source $SCRIPTPATH/initHomeAliases
source $SCRIPTPATH/initHomeBin

source  ~/bin/initShell
