#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

source $SCRIPTPATH/reset
source $SCRIPTPATH/initGlobalEnvironmentVariables
source $SCRIPTPATH/initGlobalAliases
source $SCRIPTPATH/initGlobalBin

source  ~/bin/initShell
