#!/bin/bash


get_script_dir()
{
  SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  echo "$( cd -P "$( dirname "$SOURCE" )" && pwd )"
}

get_module_bashing_dir() {
	echo $(bash -c 'read -e -p "Where you want the module bashing directory to be? Make sure to use absolute path: " MODULE_BASHING_DIR; echo "MODULE_BASHING_DIR is set to $MODULE_BASHING_DIR"')
}

get_setup_dir() {
	echo "$(get_script_dir)/setup"
}

show_initial_message() {
	echo "Working magic for osx"
}

run_setup_aliases() {
	source "$(get_setup_dir)/setup.aliases"
}

run_setup_bin() {
	source "$(get_setup_dir)/setup.bin"
}

run_setup_envvars() {
	source "$(get_setup_dir)/setup.envvars"
}

run_setup_wiring() {
	source "$(get_setup_dir)/setup.wiring"
}


show_initial_message
run_setup_aliases
run_setup_bin
run_setup_envvars
run_setup_wiring





